#!/bin/bash

BUILD_DIR='build'
SO_NAME="$BUILD_DIR/libsonic.so"

function build_py() {
    python3 setup.py install
}

function build() {
    mkdir -p $BUILD_DIR
    echo "building sonic.c..."
    gcc -shared -Wl,-soname,libsonic -o $SO_NAME -fPIC -lwiringPi -lpigpio sonic.c
    return $?
}

function cleanup() {
    if [ ! $BUILD_DIR == '' ]; then
        sudo rm -rf $BUILD_DIR
    fi
}

function is_lib_installed() {
    ldconfig -p | grep $1
    return $?
}

function install_wiringpi() {
    echo "wiringpi should be preinstalled on raspbian."
    mkdir -p "$BUILD_DIR/"
    pushd "$BUILD_DIR/"

    git clone https://github.com/WiringPi/WiringPi wiringpi
    cd wiringpi
    ./build

    popd
}

function install_pigpio() {
    mkdir -p "$BUILD_DIR/pigpio"
    pushd "$BUILD_DIR/pigpio"

    wget https://github.com/joan2937/pigpio/archive/master.zip
    unzip master.zip
    cd pigpio-master
    make
    sudo make install

    popd
}

function install() {
    cleanup

    if [[ ! $(is_lib_installed 'wiringPi') ]]; then
        echo "installing wiringpi..."
        install_wiringpi
    fi

    if [[ ! $(is_lib_installed 'pigpio') ]]; then
        echo "installing pigpio..."
        install_pigpio
    fi

    build

    build_py

    if [[ $? == 0 ]]; then
        echo "copying to /usr/local/lib"
        sudo cp $SO_NAME /usr/local/lib/libsonic.so

        echo "setting user rights..."
        sudo chmod 0755 /usr/local/lib/libsonic.so
    else
        echo "errors occurred. stopping installation."
    fi

    echo "done!"
}

install
